# Generated by Django 3.2.5 on 2021-07-15 23:25

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('subjects_taught', models.CharField(blank=True, max_length=255, null=True, validators=[teachers.models.restrict_amount])),
            ],
        ),
    ]
