# Generated by Django 3.2.5 on 2021-07-16 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210716_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='csv_file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
